//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityMnagementSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.AllocateClassRooms = new HashSet<AllocateClassRoom>();
            this.CourseAssignToTeachers = new HashSet<CourseAssignToTeacher>();
            this.EnrollInACourses = new HashSet<EnrollInACourse>();
            this.Results = new HashSet<Result>();
        }
    
        public int CourseId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int DeptId { get; set; }
        public int Semester { get; set; }
        public int Credit { get; set; }
    
        public virtual ICollection<AllocateClassRoom> AllocateClassRooms { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<CourseAssignToTeacher> CourseAssignToTeachers { get; set; }
        public virtual ICollection<EnrollInACourse> EnrollInACourses { get; set; }
        public virtual ICollection<Result> Results { get; set; }
    }
}
