//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityMnagementSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.AllocateClassRooms = new HashSet<AllocateClassRoom>();
            this.Courses = new HashSet<Course>();
            this.CourseAssignToTeachers = new HashSet<CourseAssignToTeacher>();
            this.Students = new HashSet<Student>();
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int DeptId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AllocateClassRoom> AllocateClassRooms { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<CourseAssignToTeacher> CourseAssignToTeachers { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
